export const locales = ["fr", "en", "es", "de"] as const;
export type PigeonsLocale = (typeof locales)[number];

export const localeNames: Record<PigeonsLocale, string> = { fr: "Français", en: "English", es: "Español", de: "Deutsch" };

export const pigeonsCopy = {
  fr: {
    nav: { label: "Navigation principale", projects: "Projets", story: "Mon histoire", approach: "Ma boussole" }, theme: "Changer de thème", language: "Choisir la langue",
    hero: { eyebrow: "Laboratoire indépendant", title: "Des outils numériques inspirés par de vraies rencontres.", text: "Pigeons est mon espace personnel de création. J’y construis des projets pour apprendre, expérimenter et essayer de créer des choses utiles aux autres.", cta: "Découvrir mon histoire", note: "Indépendant, curieux, en construction." },
    about: { eyebrow: "Derrière Pigeons", title: "Je m’appelle Santiago. Je construis pour rester curieux et rendre des idées utiles.", text: "Après cinq années d’études en informatique et plusieurs années d’expérience, mon parcours m’a ramené en cuisine. Je n’ai pourtant jamais vraiment quitté le code. Pigeons est devenu le lieu où ces deux mondes se rencontrent." },
    projects: { eyebrow: "Premier projet concret", title: "Tout a commencé avec EXCI.", intro: "Une discussion en cuisine, un besoin réel et l’envie d’utiliser ce que je savais faire pour aider.", first: "Premier projet Pigeons", exciTitle: "Préparer un examen important sans apprendre dans le stress.", exciText: "EXCI accompagne la préparation à l’examen civique français avec des questions d’entraînement, des quiz et un suivi personnel.", available: "Disponible sur le web", soon: "iPhone et Android bientôt disponibles", cta: "Découvrir EXCI" },
    story: { eyebrow: "Pourquoi j’ai créé Pigeons", title: "Ce projet n’est pas né d’un pitch. Il est né de rencontres.", intro: "Je pensais poursuivre naturellement ma carrière dans l’informatique. Après mes études, je n’arrivais pourtant plus à y trouver ma place professionnellement. Je suis retourné travailler en cuisine, un métier que je connaissais et qui me permet aujourd’hui de vivre.", turningPoint: "Mais je n’ai jamais vraiment quitté l’informatique.", chapters: [
      { kicker:"Le retour en cuisine", title:"Un détour qui a remis le réel au centre.", paragraphs:["En cuisine, j’ai rencontré des personnes venues de nombreux pays. Leurs histoires, leurs projets et leurs difficultés ont changé les questions que je me posais devant un écran.","C’est là que l’envie de coder a retrouvé une direction concrète."] },
      { kicker:"Une rencontre, puis EXCI", title:"Aider à préparer l’examen civique.", paragraphs:["Plusieurs collègues se préparaient à l’examen civique pour leur parcours vers la nationalité française. En discutant avec eux, j’ai compris combien il pouvait être difficile de réviser et de s’entraîner sereinement."], quote:"Pourquoi ne pas utiliser ce que je sais faire pour créer quelque chose qui puisse les aider ?" },
      { kicker:"Puis j’ai rencontré Aisha", title:"Apprendre seule, même quand je ne suis pas là.", paragraphs:["Aisha vient de Côte d’Ivoire. Elle n’a pas eu la possibilité de faire des études, mais elle avance avec une volonté immense. Pendant un été plus calme, j’ai commencé à lui donner quelques leçons de lecture et d’écriture.","Ces moments ont fait naître une nouvelle idée : créer un outil qui lui permette de continuer à son rythme, de manière plus autonome."] },
      { kicker:"La naissance de Pigeons", title:"Donner une maison à toutes ces idées.", paragraphs:["EXCI, Aisha et les projets qui viendront n’ont pas besoin de ressembler à ceux d’une grande entreprise. Ils ont besoin d’une raison d’exister et de la liberté d’évoluer.","J’ai compris que Pigeons serait cet espace : personnel, expérimental et ancré dans la vraie vie."] }
    ], sandboxEyebrow:"Alors, Pigeons, c’est quoi ?", sandboxTitle:"Pigeons.click, c’est mon bac à sable.", sandboxText:"J’y transforme une rencontre, un problème, une envie ou parfois une idée un peu bizarre en projet concret. Je crée pour aider, continuer à coder, découvrir de nouvelles technologies et transmettre ce que j’apprends.", reasons:["Une personne à aider","Un problème à résoudre","Quelque chose à apprendre","Une bonne idée à essayer"], closing:"Je suis Santiago LISBOA, et Pigeons est l’endroit où je construis tout ça." },
    approach: { eyebrow:"Ma boussole", title:"Ce que je veux garder, projet après projet.", items:[{ n:"01", title:"Une raison de construire", text:"Une personne à aider, un problème à résoudre ou quelque chose que j’ai envie d’apprendre." },{ n:"02", title:"Clair dès le départ", text:"Des mots compréhensibles et des parcours qui ne demandent pas de mode d’emploi." },{ n:"03", title:"Humain par défaut", text:"Je conçois à partir de situations vécues, avec leurs contraintes et leurs nuances." },{ n:"04", title:"Le droit d’essayer", text:"Tester, me tromper, apprendre et recommencer font partie du travail." }] },
    footer: { line:"Des projets numériques nés de la vraie vie.", created:"Créé et géré par Santiago LISBOA", legal:"Mentions légales", copyright:"© 2026 Pigeons" }
  },
  en: {
    nav: { label:"Primary navigation", projects:"Projects", story:"My story", approach:"My compass" }, theme:"Change theme", language:"Choose language",
    hero: { eyebrow:"Independent digital lab", title:"Digital tools inspired by real encounters.", text:"Pigeons is my personal space for making things. I build projects here to learn, experiment and try to create something genuinely useful for others.", cta:"Read my story", note:"Independent, curious, always evolving." },
    about: { eyebrow:"Behind Pigeons", title:"I’m Santiago. I build to stay curious and turn ideas into something useful.", text:"After five years studying computer science and several years of professional experience, my path led me back to working in a kitchen. I never really left code behind. Pigeons is where those two worlds now meet." },
    projects: { eyebrow:"The first real project", title:"It started with EXCI.", intro:"A kitchen conversation, a real need and the desire to use what I knew to help.", first:"First Pigeons project", exciTitle:"Preparing for an important exam without learning under pressure.", exciText:"EXCI helps people prepare for the French civic exam with practice questions, quizzes and personal progress tracking.", available:"Available on the web", soon:"iPhone and Android coming soon", cta:"Discover EXCI" },
    story: { eyebrow:"Why I created Pigeons", title:"This project did not start with a pitch. It started with people.", intro:"I expected to carry on with a career in tech. After graduating, though, I could no longer find my place in the industry. I went back to working in a kitchen, a job I already knew and which supports me today.", turningPoint:"But I never really left computing behind.", chapters:[
      { kicker:"Back in the kitchen", title:"A detour that brought real life back into focus.", paragraphs:["I met people from many different countries in the kitchen. Their stories, plans and difficulties changed the questions I asked whenever I sat down at a computer.","That is where coding found a tangible purpose again."] },
      { kicker:"One encounter, then EXCI", title:"Helping people prepare for the civic exam.", paragraphs:["Several colleagues were studying for the civic exam on their path towards French citizenship. Talking with them showed me how difficult calm, effective practice could be."], quote:"Why not use what I know to build something that could help them?" },
      { kicker:"Then I met Aisha", title:"Learning independently, even when I am not there.", paragraphs:["Aisha is from Côte d’Ivoire. She never had the opportunity to study, yet her determination to move forward is remarkable. During a quieter summer, I began helping her learn to read and write.","Those lessons sparked a new idea: a tool that would let her continue at her own pace and become more independent."] },
      { kicker:"Pigeons takes shape", title:"A home for all these ideas.", paragraphs:["EXCI, Aisha and whatever comes next do not need to look like products from a large company. They need a reason to exist and the freedom to evolve.","I realised Pigeons could be that space: personal, experimental and grounded in real life."] }
    ], sandboxEyebrow:"So, what is Pigeons?", sandboxTitle:"Pigeons.click is my sandbox.", sandboxText:"It is where I turn an encounter, a problem, a wish or sometimes a slightly odd idea into a real project. I build to help, to keep coding, to discover new technologies and to share what I learn.", reasons:["Someone to help","A problem to solve","Something to learn","A good idea to try"], closing:"I’m Santiago LISBOA, and Pigeons is where I build all of it." },
    approach:{ eyebrow:"My compass", title:"What I want to preserve from one project to the next.", items:[{ n:"01", title:"A reason to build", text:"Someone to help, a problem to solve or something I genuinely want to learn." },{ n:"02", title:"Clear from the start", text:"Plain words and journeys that do not require an instruction manual." },{ n:"03", title:"Human by default", text:"I design from lived situations, with all their constraints and nuances." },{ n:"04", title:"Room to experiment", text:"Trying, getting things wrong, learning and starting again are part of the work." }] },
    footer:{ line:"Digital projects born from real life.", created:"Created and run by Santiago LISBOA", legal:"Legal notice", copyright:"© 2026 Pigeons" }
  },
  es: {
    nav:{ label:"Navegación principal", projects:"Proyectos", story:"Mi historia", approach:"Mi brújula" }, theme:"Cambiar el tema", language:"Elegir idioma",
    hero:{ eyebrow:"Laboratorio digital independiente", title:"Herramientas digitales inspiradas en encuentros reales.", text:"Pigeons es mi espacio personal de creación. Aquí desarrollo proyectos para aprender, experimentar e intentar crear cosas realmente útiles para los demás.", cta:"Conocer mi historia", note:"Independiente, curioso y siempre en construcción." },
    about:{ eyebrow:"Detrás de Pigeons", title:"Soy Santiago. Creo para seguir siendo curioso y convertir ideas en algo útil.", text:"Después de cinco años estudiando informática y varios años de experiencia profesional, mi camino me llevó de nuevo a una cocina. Sin embargo, nunca abandoné del todo el código. Pigeons es el lugar donde hoy se encuentran esos dos mundos." },
    projects:{ eyebrow:"El primer proyecto concreto", title:"Todo empezó con EXCI.", intro:"Una conversación en la cocina, una necesidad real y las ganas de usar lo que sabía para ayudar.", first:"Primer proyecto Pigeons", exciTitle:"Preparar un examen importante sin aprender bajo presión.", exciText:"EXCI ayuda a preparar el examen cívico francés con preguntas de práctica, cuestionarios y seguimiento personal.", available:"Disponible en la web", soon:"Próximamente en iPhone y Android", cta:"Descubrir EXCI" },
    story:{ eyebrow:"Por qué creé Pigeons", title:"Este proyecto no nació de un discurso comercial. Nació de encuentros.", intro:"Pensaba continuar mi carrera en la informática de forma natural. Sin embargo, después de mis estudios ya no conseguía encontrar mi lugar profesionalmente. Volví a trabajar en una cocina, un oficio que conocía y que hoy me permite vivir.", turningPoint:"Pero nunca abandoné realmente la informática.", chapters:[
      { kicker:"La vuelta a la cocina", title:"Un desvío que volvió a poner la realidad en el centro.", paragraphs:["En la cocina conocí a personas de muchos países. Sus historias, sus proyectos y sus dificultades cambiaron las preguntas que me hacía delante de una pantalla.","Fue allí donde programar volvió a tener una dirección concreta."] },
      { kicker:"Un encuentro, después EXCI", title:"Ayudar a preparar el examen cívico.", paragraphs:["Varios compañeros se preparaban para el examen cívico como parte de su camino hacia la nacionalidad francesa. Hablando con ellos comprendí lo difícil que podía ser estudiar y practicar con tranquilidad."], quote:"¿Por qué no usar lo que sé hacer para crear algo que pueda ayudarles?" },
      { kicker:"Después conocí a Aisha", title:"Aprender sola, incluso cuando yo no estoy.", paragraphs:["Aisha es de Costa de Marfil. No tuvo la oportunidad de estudiar, pero avanza con una voluntad enorme. Durante un verano más tranquilo, empecé a ayudarla a leer y escribir.","Esas clases hicieron nacer otra idea: una herramienta con la que pudiera continuar a su ritmo y ganar autonomía."] },
      { kicker:"Nace Pigeons", title:"Un hogar para todas estas ideas.", paragraphs:["EXCI, Aisha y los próximos proyectos no tienen que parecer productos de una gran empresa. Necesitan una razón para existir y libertad para evolucionar.","Entendí que Pigeons sería ese espacio: personal, experimental y conectado con la vida real."] }
    ], sandboxEyebrow:"Entonces, ¿qué es Pigeons?", sandboxTitle:"Pigeons.click es mi caja de arena.", sandboxText:"Es el lugar donde convierto un encuentro, un problema, un deseo o, a veces, una idea un poco extraña en un proyecto real. Creo para ayudar, seguir programando, descubrir nuevas tecnologías y compartir lo que aprendo.", reasons:["Una persona a la que ayudar","Un problema que resolver","Algo que aprender","Una buena idea que probar"], closing:"Soy Santiago LISBOA, y Pigeons es el lugar donde construyo todo eso." },
    approach:{ eyebrow:"Mi brújula", title:"Lo que quiero conservar de un proyecto al siguiente.", items:[{ n:"01", title:"Una razón para crear", text:"Una persona a la que ayudar, un problema que resolver o algo que de verdad quiero aprender." },{ n:"02", title:"Claro desde el principio", text:"Palabras comprensibles y recorridos que no necesitan manual." },{ n:"03", title:"Humano por defecto", text:"Diseño a partir de situaciones reales, con sus límites y sus matices." },{ n:"04", title:"El derecho a probar", text:"Probar, equivocarme, aprender y volver a empezar forman parte del trabajo." }] },
    footer:{ line:"Proyectos digitales nacidos de la vida real.", created:"Creado y gestionado por Santiago LISBOA", legal:"Aviso legal", copyright:"© 2026 Pigeons" }
  },
  de: {
    nav:{ label:"Hauptnavigation", projects:"Projekte", story:"Meine Geschichte", approach:"Mein Kompass" }, theme:"Darstellung wechseln", language:"Sprache wählen",
    hero:{ eyebrow:"Unabhängiges Digitallabor", title:"Digitale Werkzeuge, inspiriert von echten Begegnungen.", text:"Pigeons ist mein persönlicher Raum zum Gestalten. Hier entwickle ich Projekte, um zu lernen, zu experimentieren und etwas zu schaffen, das anderen wirklich nützt.", cta:"Meine Geschichte lesen", note:"Unabhängig, neugierig und immer im Werden." },
    about:{ eyebrow:"Hinter Pigeons", title:"Ich bin Santiago. Ich baue, um neugierig zu bleiben und Ideen nützlich zu machen.", text:"Nach fünf Jahren Informatikstudium und mehreren Jahren Berufserfahrung führte mich mein Weg zurück in eine Küche. Den Code habe ich trotzdem nie wirklich verlassen. Pigeons ist der Ort, an dem diese beiden Welten heute zusammenkommen." },
    projects:{ eyebrow:"Das erste konkrete Projekt", title:"Alles begann mit EXCI.", intro:"Ein Gespräch in der Küche, ein echter Bedarf und der Wunsch, mit meinem Wissen zu helfen.", first:"Erstes Pigeons-Projekt", exciTitle:"Für eine wichtige Prüfung lernen, ohne unnötigen Druck.", exciText:"EXCI unterstützt bei der Vorbereitung auf die französische Einbürgerungsprüfung mit Übungsfragen, Quizzen und persönlichem Lernfortschritt.", available:"Im Web verfügbar", soon:"iPhone und Android folgen bald", cta:"EXCI entdecken" },
    story:{ eyebrow:"Warum ich Pigeons gegründet habe", title:"Dieses Projekt begann nicht mit einem Pitch. Es begann mit Begegnungen.", intro:"Eigentlich wollte ich meine Laufbahn in der Informatik fortsetzen. Nach dem Studium fand ich dort beruflich jedoch keinen Platz mehr. Also ging ich zurück in eine Küche, eine Arbeit, die ich kannte und von der ich heute lebe.", turningPoint:"Aber die Informatik habe ich nie wirklich verlassen.", chapters:[
      { kicker:"Zurück in der Küche", title:"Ein Umweg, der das echte Leben wieder in den Mittelpunkt rückte.", paragraphs:["In der Küche traf ich Menschen aus vielen Ländern. Ihre Geschichten, Pläne und Schwierigkeiten veränderten die Fragen, die ich mir vor dem Bildschirm stellte.","Dort bekam das Programmieren wieder eine konkrete Richtung."] },
      { kicker:"Eine Begegnung, dann EXCI", title:"Bei der Vorbereitung auf die Einbürgerungsprüfung helfen.", paragraphs:["Mehrere Kolleginnen und Kollegen lernten für die Einbürgerungsprüfung auf ihrem Weg zur französischen Staatsbürgerschaft. In unseren Gesprächen verstand ich, wie schwierig ruhiges und wirksames Üben sein kann."], quote:"Warum sollte ich mein Wissen nicht nutzen, um etwas zu bauen, das ihnen hilft?" },
      { kicker:"Dann traf ich Aisha", title:"Selbstständig lernen, auch wenn ich nicht da bin.", paragraphs:["Aisha kommt aus der Côte d’Ivoire. Sie hatte keine Möglichkeit zu studieren, geht ihren Weg aber mit großer Entschlossenheit. In einem ruhigeren Sommer half ich ihr beim Lesen und Schreiben.","Aus diesen Stunden entstand eine neue Idee: ein Werkzeug, mit dem sie in ihrem eigenen Tempo weiterlernen und selbstständiger werden kann."] },
      { kicker:"Pigeons entsteht", title:"Ein Zuhause für all diese Ideen.", paragraphs:["EXCI, Aisha und alles, was danach kommt, müssen nicht wie Produkte eines Großunternehmens aussehen. Sie brauchen einen Grund zu existieren und die Freiheit, sich zu verändern.","Mir wurde klar, dass Pigeons genau dieser Raum sein kann: persönlich, experimentell und im echten Leben verankert."] }
    ], sandboxEyebrow:"Was ist Pigeons also?", sandboxTitle:"Pigeons.click ist mein Sandkasten.", sandboxText:"Hier verwandle ich eine Begegnung, ein Problem, einen Wunsch oder manchmal eine etwas schräge Idee in ein echtes Projekt. Ich baue, um zu helfen, weiter zu programmieren, neue Technologien kennenzulernen und mein Wissen zu teilen.", reasons:["Ein Mensch, dem ich helfen kann","Ein Problem, das ich lösen kann","Etwas, das ich lernen kann","Eine gute Idee zum Ausprobieren"], closing:"Ich bin Santiago LISBOA, und Pigeons ist der Ort, an dem ich all das baue." },
    approach:{ eyebrow:"Mein Kompass", title:"Was ich von Projekt zu Projekt bewahren möchte.", items:[{ n:"01", title:"Ein Grund, etwas zu bauen", text:"Ein Mensch, dem ich helfen kann, ein Problem oder etwas, das ich wirklich lernen möchte." },{ n:"02", title:"Von Anfang an klar", text:"Verständliche Worte und Wege, die keine Anleitung brauchen." },{ n:"03", title:"Menschlich gedacht", text:"Ich gestalte aus echten Situationen heraus, mit all ihren Zwängen und Nuancen." },{ n:"04", title:"Raum zum Ausprobieren", text:"Versuchen, scheitern, lernen und neu anfangen gehören für mich dazu." }] },
    footer:{ line:"Digitale Projekte aus dem echten Leben.", created:"Erstellt und betrieben von Santiago LISBOA", legal:"Impressum", copyright:"© 2026 Pigeons" }
  }
} as const;

export function isPigeonsLocale(value: string): value is PigeonsLocale { return locales.includes(value as PigeonsLocale); }
