import Link from "next/link";
import { exciMetadata, serializeJsonLd } from "@/lib/seo";
export const metadata = exciMetadata("Comment préparer l’examen civique", "Comprendre l’examen civique de naturalisation, distinguer les ressources officielles des questions d’entraînement et organiser ses révisions avec EXCI.", "/preparer-examen-civique");
export default function Guide() {
 const breadcrumbs = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "EXCI", item: "https://exci.pigeons.click/" }, { "@type": "ListItem", position: 2, name: "Préparer l’examen civique", item: "https://exci.pigeons.click/preparer-examen-civique" }] };
 return <article className="legal-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(breadcrumbs) }} /><nav aria-label="Fil d’Ariane"><Link href="/">EXCI</Link> / Guide de préparation</nav><header><p className="eyebrow">Réviser avec EXCI</p><h1 className="page-title">Comment préparer l’examen civique français</h1><p className="page-lead">Comprendre les notions, pratiquer régulièrement et revenir sur ses erreurs : une méthode simple pour préparer la partie civique de votre démarche de naturalisation.</p></header>
 <section><h2>Comprendre l’épreuve avant de réviser</h2><p>Depuis 2026, l’examen civique fait partie de certaines démarches de séjour et de naturalisation. Il existe des mentions distinctes : vérifiez celle qui correspond à votre démarche. L’épreuve officielle comporte 40 questions et dure au maximum 45 minutes.</p><p>Les conditions, les éventuelles dispenses et les modalités d’inscription se vérifient auprès de l’administration. EXCI aide à réviser ; il ne délivre aucune attestation officielle et ne remplace pas l’ensemble de la préparation à la naturalisation.</p><p>Source consultée le 2 octobre 2026 : <a href="https://formation-civique.interieur.gouv.fr/examen-civique/" target="_blank" rel="noopener noreferrer">informations et ressources officielles du ministère de l’Intérieur</a>. Pour une démarche en 2027 ou plus tard, consultez cette source à nouveau : les règles peuvent évoluer.</p></section>
 <section><h2>Questions officielles et questions d’entraînement</h2><p>L’administration publie des questions de connaissance. Les mises en situation de l’épreuve ne sont pas toutes rendues publiques. Une liste de connaissances ne permet donc pas de prédire votre questionnaire.</p><p>EXCI utilise une banque pédagogique avec réponses et explications. Sa provenance est héritée du projet initial, sans validation documentaire individuelle de toutes les questions. Les quiz ne sont pas présentés comme les questions exactes de l’examen officiel.</p></section>
 <section><h2>Une routine de révision en quatre étapes</h2><ol><li>Commencez par une courte série de <Link href="/quiz">questions d’entraînement à l’examen civique</Link>.</li><li>Lisez l’explication après une erreur et reformulez la notion avec vos propres mots.</li><li>Utilisez vos favoris pour retrouver les notions difficiles. Votre progression reste sur cet appareil ; un compte permet la synchronisation.</li><li>Essayez l’<Link href="/exam">examen blanc de 40 questions en 45 minutes</Link> pour pratiquer la gestion du temps. Le tirage pédagogique ne reproduit pas la répartition complète de l’épreuve officielle.</li></ol></section>
 <section><h2>Quelles notions travailler ?</h2><p>Dans EXCI, les questions sont regroupées par principes et valeurs, institutions, vie en société, histoire et culture, géographie, travail et économie. Ces six catégories internes facilitent la révision ; elles ne constituent pas le découpage officiel du programme.</p><p>Comparez vos révisions aux ressources officielles. Un résultat dans l’application donne un repère pour travailler, sans garantir l’issue de votre démarche.</p></section>
 <section><h2>Un projet humain et indépendant</h2><p>EXCI est un projet du studio <a href="https://pigeons.click/">Pigeons</a>, créé par <a href="https://www.linkedin.com/in/santiago-lisboa/" target="_blank" rel="noopener noreferrer">Santiago LISBOA</a>. Si vous souhaitez aussi travailler la lecture en français, découvrez <a href="https://aicha.pigeons.click/apprendre-a-lire">l’approche de lecture progressive d’Aicha</a>.</p></section></article>;
}
